[package]
authors = [
  "Jyun-Yan You <jyyou.tw@gmail.com>",
  "Emilio Cobos Álvarez <emilio@crisal.io>",
  "Nick Fitzgerald <fitzgen@gmail.com>",
  "The Servo project developers",
]
description = "Automatically generates Rust FFI bindings to C and C++ libraries."
keywords = ["bindings", "ffi", "code-generation"]
categories = ["external-ffi-bindings", "development-tools::ffi"]
license = "BSD-3-Clause"
name = "bindgen"
readme = "README.md"
repository = "https://github.com/rust-lang-nursery/rust-bindgen"
documentation = "https://docs.rs/bindgen"
version = "0.35.0"
build = "build.rs"

include = [
  "Cargo.toml",
  "build.rs",
  "src/*.rs",
  "src/**/*.rs",
]

[badges]
travis-ci = { repository = "rust-lang-nursery/rust-bindgen" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "bindgen"
path = "src/main.rs"
doc = false

[dev-dependencies]
diff = "0.1"
clap = "2"
shlex = "0.1"

[dependencies]
cexpr = "0.2"
cfg-if = "0.1.0"
# This kinda sucks: https://github.com/rust-lang/cargo/issues/1982
clap = "2"
clang-sys = { version = "0.22.0", features = ["runtime", "clang_3_9"] }
lazy_static = "1"
peeking_take_while = "0.1.2"
proc-macro2 = { version = "0.3.1", default-features = false }
quote = { version = "0.5.1", default-features = false }
regex = "0.2"
which = "1.0.2"

[dependencies.env_logger]
optional = true
version = "0.5"

[dependencies.log]
optional = true
version = "0.4"

[features]
default = ["logging", "proc-macro"]
logging = ["env_logger", "log"]
proc-macro = ["proc-macro2/proc-macro", "quote/proc-macro"]
static = []

# These features only exist for CI testing -- don't use them if you're not hacking
# on bindgen!
testing_only_docs = []
testing_only_extra_assertions = []
testing_only_libclang_4 = []
testing_only_libclang_3_9 = []
testing_only_libclang_3_8 = []
